### ISSUE TITLE
Tag a first release

### ISSUE THREAD

**Issue by simba909** [Apple-Actions/upload-testflight-build#3]
Hi!

I just recently found the work that you've put here in Apple-Actions, and it really simplified migrating one of the project workflows that I'm working on from Azure DevOps 👍 Thanks a bunch!

With that said, can I request that you tag a v1 of this action? It would really help us out 🙂

**Comment by raven** [comment]
Please ☝️  @orj

**Comment by orj** [comment]
Will do.

**Comment by simba909** [comment]
Closing now that there’s a release tagged: https://github.com/Apple-Actions/upload-testflight-build/releases/tag/v1

Thank you for swift (heh) feedback @orj ! 👏
