### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by sikandernoori** [Apple-Actions/upload-testflight-build#37]
getting warning on Github Actions.

I know it doesn't break anything but would be good to have warning free workflow.

 
--
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: apple-actions/upload-testflight-build@v1Show less
 

<br class="Apple-interchange-newline">

**Comment by jopmiddelkamp** [comment]
I'm also getting this warning.
